default:
	cat Makefile

update:
	composer update

build:
	npm run dev

start:
	php artisan serve

migrate:
	php artisan migrate



publish:
	php artisan livewire:publish
	# [/vendor/livewire/livewire/config/livewire.php]  --> [/config/livewire.php]
	# [/vendor/livewire/livewire/src/views/pagination] --> [/resources/views/vendor/livewire]

	
